# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{render_component_sf}
  s.version = "2.3.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Heinemeier Hansson"]
  s.date = %q{2011-02-01}
  s.description = %q{Components allow you to call other actions for their rendered response while executing another action}
  s.email = %q{david@loudthinking.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README",
    "Rakefile",
    "init.rb",
    "lib/render_component.rb",
    "lib/render_component/components.rb",
    "lib/render_component/version.rb",
    "lib/render_component_sf.rb",
    "render_component_sf.gemspec",
    "test/abstract_unit.rb",
    "test/components_test.rb"
  ]
  s.homepage = %q{http://github.com/sflinter/render_component}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{render actions in other controllers for their rendered response}
  s.test_files = [
    "test/abstract_unit.rb",
    "test/components_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<rcov>, ["= 0.9.9"])
      s.add_runtime_dependency(%q<rails>, ["~> 2.3.10"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, ["= 0.9.9"])
      s.add_dependency(%q<rails>, ["~> 2.3.10"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, ["= 0.9.9"])
    s.add_dependency(%q<rails>, ["~> 2.3.10"])
  end
end

